name: On push

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Update version in setup.py
      run: sed -i "s/{{VERSION_PLACEHOLDER}}/0.0.1/g" setup.py

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    
    - name: Run unit tests
      run: pytest

  build-and-publish:
    needs: [test]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Generate release tag
      uses: amitsingh-007/next-release-tag@v2.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release_tag }}
        release_name: Release ${{ env.release_tag }}

    - name: Update version in setup.py
      run: sed -i "s/{{VERSION_PLACEHOLDER}}/${{ env.release_tag }}/g" setup.py

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Build a binary wheel
      run: python setup.py sdist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{secrets.PYPI_API_TOKEN}}
